### ISSUE TITLE
Wrong parsing pseudo-classes/elements inside media queries

### ISSUE THREAD

**Issue by stepaluch** [JakubOnderka/CSSTidy#1]
Pseudo-classes/elements in media queries blocks are parsed(?) wrong :

``` css
@media screen {
  a:active{
    color: teal
  }
}
```

converts to :

``` css
@media screen{a:active{;color:teal}
```

with warnings in console :

``` text
     Warning Added semicolon to the end of declaration 
    Warning Invalid property in CSS3.0: a 
```
